name = "MoebiusTranscendental"
version = "0.1.0"
defaultTargets = ["MoebiusTranscendental"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "MoebiusTranscendental"
